# NUMPY

In [11]:
import numpy as np

## 1D array

In [12]:
a=np.array([10,20,30,40,50,60])

In [13]:
a

array([10, 20, 30, 40, 50, 60])

### Attributes of arrays
#### dtype , ndim, size, shape

In [14]:
a.dtype

dtype('int32')

In [15]:
a.shape

(6,)

In [16]:
a.ndim

1

In [17]:
a.size

6

In [18]:
a[0]

10

In [19]:
a[4]

50

## Multi dimensional array

In [20]:
a_2d=np.array([[10,20,30],[22,44,66]])

In [21]:
a_2d

array([[10, 20, 30],
       [22, 44, 66]])

In [22]:
a_2d.dtype

dtype('int32')

In [23]:
a_2d.shape

(2, 3)

In [24]:
a_2d.ndim

2

In [25]:
a_2d.size

6

In [26]:
a_2d[0]

array([10, 20, 30])

In [27]:
a_2d[0,1]

20

In [28]:
a_2d[0][1]

20

## Another type of multi dimensional arrays

In [29]:
b=np.array([[[1,2,3,4]]])

In [30]:
b

array([[[1, 2, 3, 4]]])

In [31]:
b.shape

(1, 1, 4)

In [32]:
b.ndim

3

In [33]:
b.size

4

### First element in first row

In [34]:
b[0,0,3]

4

In [35]:
a_2d=np.array([[10,20,30],[22,44,66]],dtype= float)

In [36]:
a_2d

array([[10., 20., 30.],
       [22., 44., 66.]])

In [45]:
a_big=np.array([[[11,22,33,44,55],[131,212,323,42,525],[101,202,303,404,505]],[[110,220,330,440,505],[31,12,33,42,25],[11,202,303,404,505]],[[181,282,338,448,558],[31,212,32,42,52],[701,802,303,44,50]]],dtype=float)
a_big

array([[[ 11.,  22.,  33.,  44.,  55.],
        [131., 212., 323.,  42., 525.],
        [101., 202., 303., 404., 505.]],

       [[110., 220., 330., 440., 505.],
        [ 31.,  12.,  33.,  42.,  25.],
        [ 11., 202., 303., 404., 505.]],

       [[181., 282., 338., 448., 558.],
        [ 31., 212.,  32.,  42.,  52.],
        [701., 802., 303.,  44.,  50.]]])

In [54]:
a_big.shape

(3, 3, 5)

In [47]:
a_big.ndim

3

In [48]:
a_big.size

45

In [50]:
a_big[2,1,2]

32.0

In [51]:
a_big[2][2]

array([701., 802., 303.,  44.,  50.])

In [52]:
a_full=np.full((3,5,4),7)

In [53]:
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [55]:
a_full.ndim

3

## Zeros and ones
### For the cases that we want arrays full of zeros or ones, we even have specific function

In [57]:
a_zeros=np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
b_ones=np.ones((2,3,4))
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [59]:
b_ones.ndim

3

In [60]:
e=np.empty((4,4))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23043429e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [61]:
c=np.random.random((2,2))
c

array([[0.64283941, 0.95480853],
       [0.33804897, 0.07062901]])

## Ranges
### Instead of just filling arrays with the same values, we can fill create sequences of values by specifying the boundaries. For this, we can use two different functions, namely arange and linspace. 

In [67]:
a_arange=np.arange(10)
a_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
b_arange=np.arange(10,50,5)
b_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

## linspace 
## By using linspace we also create a list from a minimum value to a maximum value. But instead of specifying the step-size, we specify the amount of values that we want to have in our list. They will all be spread evenly and have the same distance to their neighbors. 


In [69]:
c_linspace=np.linspace(0,50,2)
c_linspace

array([ 0., 50.])

In [70]:
c_linspace.ndim

1

In [71]:
w_linspace=np.linspace(0,50,30)
w_linspace

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [72]:
w_linspace.size

30

In [73]:
w_linspace2=np.linspace(0,50,25,dtype=int)
w_linspace2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

## Create some arrays and apply all the functions 

In [74]:
np.median(w_linspace2)

25.0

In [75]:
np.sum(w_linspace2)

614

In [76]:
np.sqrt(w_linspace2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [77]:
np.std(w_linspace2)

14.924020905908701

In [78]:
np.cos(w_linspace2)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])

In [79]:
np.sin(w_linspace2)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.13235175,  0.95637593, -0.66363388,
       -0.40403765,  0.99991186, -0.42818267, -0.64353813,  0.96379539,
       -0.15862267, -0.83177474,  0.85090352,  0.12357312, -0.26237485])

In [80]:
np.tan(w_linspace2)

array([ 0.00000000e+00, -2.18503986e+00,  1.15782128e+00, -2.91006191e-01,
       -6.79971146e+00,  6.48360827e-01, -6.35859929e-01,  7.24460662e+00,
        3.00632242e-01, -1.13731371e+00,  2.23716094e+00,  8.85165604e-03,
       -1.33526407e-01, -3.27370380e+00,  8.87142844e-01, -4.41695568e-01,
       -7.53130148e+01,  4.73814720e-01, -8.40771255e-01,  3.61455441e+00,
        1.60656699e-01, -1.49838734e+00,  1.61977519e+00, -1.24527568e-01,
       -2.71900612e-01])